--집합연산자
--UNION 합집합, 중복X
--UNION ALL 합집합, 중복O
--INTERSECT 교집합
--MINUS 차집합

SELECT FIRST_NAME, HIRE_DATE FROM EMPLOYEES WHERE HIRE_DATE LIKE '04%'
MINUS --INTERSECT --UNION ALL --UNION
SELECT FIRST_NAME, HIRE_DATE FROM EMPLOYEES WHERE DEPARTMENT_ID = 20;

--주의할점 - 컬럼의 갯수가 일치해야 가능 SELECT 안의 컬럼이 2개면 밑에도 2개여야 한다.


--가짜 데이터 만들어서 사용할 때
SELECT 'HONG' AS 이름, 20 AS 나이 FROM DUAL
UNION ALL
SELECT 'LEE', 30 FROM DUAL
UNION ALL
SELECT 'CHOI', 23 FROM DUAL;

--분석함수
--SQLD시험에서 무조건 등장한다.**

SELECT FIRST_NAME,
       SALARY,
       RANK() OVER (ORDER BY SALARY DESC) AS 중복순위,
       DENSE_RANK() OVER(ORDER BY SALARY DESC) AS 중복없는순위,
       ROW_NUMBER() OVER(ORDER BY SALARY DESC) AS 일련번호
    FROM EMPLOYEES;
