-- 제약조건
-- NOT NULL - NULL을 허용하지 않음
-- UNIQUE KEY - 중복X, NULL허용
-- PK - 중복X, NULL X, 테이블에서 1개만 지정이 된다(집합으로는 가능)
-- FOREIGN KEY - 참조되는 테이블의 PK를 넣어놓은 키, 중복 O, NULL 허용
-- CHECK - 컬럼에 대한 데이터 제한

SELECT * FROM USER_CONSTRAINTS;

-- 1. 열레벨 정의
CREATE TABLE DEPTS (
    DEPT_NO NUMBER(2)           CONSTRAINT DEPTS_DEPT_NO_PK PRIMARY KEY,
    DEPT_NAME VARCHAR2(30)      CONSTRAINT DEPTS_DEPT_NAME_NN NOT NULL,
    DEPT_DATE DATE              DEFAULT SYSDATE, --제약조건은 아니고 기본값으로 SYSDATE가 들어감    
    DEPT_PHONE VARCHAR2(30)     CONSTRAINT DEPTS_DEPT_PHONE_UK UNIQUE,
    DEPT_GENDER CHAR(1)         CONSTRAINT DEPTS_DEPT_GENDER_CK CHECK(DEPT_GENDER IN ('F','M')),
    LOCA_ID NUMBER(4)           CONSTRAINT DEPTS_LOCA_ID_FK REFERENCES LOCATIONS (LOCATION_ID) -- FOREIGN KEY 로케이션테이블(로케이션아이디)
);

INSERT INTO DEPTS(DEPT_NO, DEPT_NAME, DEPT_PHONE, DEPT_GENDER, LOCA_ID)
VALUES (1, NULL, '010-1111-2222','F',1700); -- 이름 제약조건 위배 - NOT NULL

INSERT INTO DEPTS(DEPT_NO, DEPT_NAME, DEPT_PHONE, DEPT_GENDER, LOCA_ID)
VALUES (1, '홍길동', '010-1111-2222','X',1700); -- GENDER 제약조건 위배 - CHECK IN('F','M')

INSERT INTO DEPTS(DEPT_NO, DEPT_NAME, DEPT_PHONE, DEPT_GENDER, LOCA_ID)
VALUES (1, '홍길동', '010-1111-2222','F',100); -- 무결성 제약조건 위배 - LOCATION 테이블의 PK에 100이란 값이 없기 때문에

INSERT INTO DEPTS(DEPT_NO, DEPT_NAME, DEPT_PHONE, DEPT_GENDER, LOCA_ID)
VALUES (1, 'HONG', '010-1111-2222','F',1700); -- 가능

INSERT INTO DEPTS(DEPT_NO, DEPT_NAME, DEPT_PHONE, DEPT_GENDER, LOCA_ID)
VALUES (2, 'HONG', '010-1111-2222','F',1700); -- UNIQUE제약 위배 - PHONE 컬럼은 UNIQUE

DROP TABLE DEPTS;

-- CONSTRAINT는 생략이 가능함
CREATE TABLE DEPTS (
    DEPT_NO NUMBER(2)           PRIMARY KEY,
    DEPT_NAME VARCHAR2(30)      NOT NULL,
    DEPT_DATE DATE              DEFAULT SYSDATE, --제약조건은 아니고 기본값으로 SYSDATE가 들어감    
    DEPT_PHONE VARCHAR2(30)     UNIQUE,
    DEPT_GENDER CHAR(1)         CHECK(DEPT_GENDER IN ('F','M')),
    LOCA_ID NUMBER(4)           REFERENCES LOCATIONS (LOCATION_ID) -- FOREIGN KEY 로케이션테이블(로케이션아이디)
);

-- 2. 테이블레벨 정의
CREATE TABLE DEPTS (
    DEPT_NO NUMBER(2),
    DEPT_NAME VARCHAR2(30)      NOT NULL, -- NOT NULL 은 열레벨에서 지정해줘야 함.
    DEPT_DATE DATE              DEFAULT SYSDATE, --제약조건은 아니고 기본값으로 SYSDATE가 들어감    
    DEPT_PHONE VARCHAR2(30),
    DEPT_GENDER CHAR(1),
    LOCA_ID NUMBER(4),
    CONSTRAINT DEPTS_DEPT_NO_PK PRIMARY KEY(DEPT_NO, DEPT_NAME), -- 복합키
    CONSTRAINT DEPTS_DEPT_PHONE_UK UNIQUE(DEPT_PHONE),
    CONSTRAINT DEPTS_DEPT_GENDER_CK CHECK(DEPT_GENDER IN ('F','M')),
    CONSTRAINT DEPTS_LOCA_ID_FK FOREIGN KEY (LOCA_ID) REFERENCES LOCATIONS (LOCATION_ID)    
);

DESC DEPTS;
-- 3. 제약조건의 추가, 삭제
CREATE TABLE DEPTS (
    DEPT_NO NUMBER(2),
    DEPT_NAME VARCHAR2(30)      NOT NULL,
    DEPT_DATE DATE              DEFAULT SYSDATE,
    DEPT_PHONE VARCHAR2(30),
    DEPT_GENDER CHAR(1),
    LOCA_ID NUMBER(4)
);

-- PK추가
ALTER TABLE DEPTS
    ADD CONSTRAINT DEPTS_DEPT_NO_PK PRIMARY KEY(DEPT_NO);

-- UNIQUE 추가
ALTER TABLE DEPTS
    ADD CONSTRAINT DEPTS_DEPT_PHONE_UK UNIQUE(DEPT_PHONE);
    
-- CHECK 추가
ALTER TABLE DEPTS
    ADD CONSTRAINT DEPTS_DEPT_GENDER_CK CHECK(DEPT_GENDER IN ('M','F'));
    
-- FOREIGN KEY 추가
ALTER TABLE DEPTS
    ADD CONSTRAINT DEPTS_LOCA_ID_FK FOREIGN KEY(LOCA_ID) REFERENCES LOCATIONS (LOCATION_ID);
    
-- NOT NULL은 MODIFY로 수정 가능
ALTER TABLE DEPTS
    MODIFY DEPT_NAME VARCHAR2(30) NOT NULL;
    
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'DEPTS';

-- 제약조건의 삭제
ALTER TABLE DEPTS DROP CONSTRAINT DEPTS_DEPT_GENDER_CK;

-- 마우스로 생성 가능.
DROP TABLE DEPTS;

--------------------------- 연습 문제 ---------------------------
--문제1.
--
--다음과 같은 테이블을 생성하고 데이터를 insert해보세요.
--테이블 제약조건은 아래와 같습니다. 
--조건) M_NAME 는 가변문자형 20byte, 널값을 허용하지 않음
--조건) M_NUM 은 숫자형 5자리, PRIMARY KEY 이름(mem_memnum_pk) 
--조건) REG_DATE 는 날짜형, 널값을 허용하지 않음, UNIQUE KEY 이름:(mem_regdate_uk)
--조건) SALARY 숫자형 10자리, CHECK제약 (0 보다 크다)
--조건) LOCA 숫자형 4자리, FOREIGN KEY – 참조 locations테이블(location_id) 이름:(mem_loca_loc_locid_fk)
CREATE TABLE MEM (
    M_NAME VARCHAR2(20) CONSTRAINT MEM_MNAME_NN NOT NULL,
    M_NUM NUMBER(5) CONSTRAINT MEM_MNUM_PK PRIMARY KEY,
    REG_DATE DATE CONSTRAINT MEM_REGDATE_UK UNIQUE,
    SALARY NUMBER(10) CONSTRAINT MEM_SALARY_CK CHECK(SALARY > 0),
    LOCA NUMBER(4) CONSTRAINT MEM_LOCA_LOC_LOCID_FK REFERENCES LOCATIONS (LOCATION_ID)
);
INSERT INTO MEM VALUES('AAA',1,'2018-07-01',5000,1800);
INSERT INTO MEM VALUES('BBB',2,'2018-07-02',3000,1900);
INSERT INTO MEM VALUES('CCC',3,'2018-07-03',3000,2000);
INSERT INTO MEM VALUES('DDD',4,SYSDATE,2000,2000);

SELECT * FROM MEM;

--문제2.
--도서테이블, 도서 대여 이력 테이블을 생성하려 합니다.
--도서 테이블은
--도서번호(문자) PK, 도서명(문자), 출판사(문자), 입고일(날짜)
--도서 대여 이력 테이블은
--대여번호(숫자) PK, 도서번호(문자) FK, 대여일(날짜), 반납일(날짜), 반납여부(Y/N)
--를 가집니다.
--적절한 테이블을 생성해 보세요.
CREATE TABLE LIBRARY (
    BOOK_NUM VARCHAR2(30) CONSTRAINT LIBRARY_BOOK_NUM_PK PRIMARY KEY,
    BOOK_NAME VARCHAR2(500) CONSTRAINT LIBRARY_BOOK_NAME_UK UNIQUE,
    BOOK_PUBLISHER VARCHAR2(100) CONSTRAINT LIBRARY_BOOK_PUBLISHER_NN NOT NULL,
    BOOK_DATE DATE CONSTRAINT LIBRARY_BOOK_DATE_NN NOT NULL
);

CREATE TABLE BOOK_LEND (
    BOOK_LEND_NUM NUMBER(38) CONSTRAINT BOOK_LEND_BOOK_LEND_NUM_PK PRIMARY KEY,
    BOOK_NUM VARCHAR2(30) CONSTRAINT BOOK_LEND_BOOK_NUM_FK REFERENCES LIBRARY (BOOK_NUM),
    BOOK_LEND_DATE DATE CONSTRAINT BOOK_LEND_BOOK_LEND_DATE_NN NOT NULL,
    BOOK_RETURN_DATE DATE DEFAULT SYSDATE,
    BOOK_RETURN_YN CHAR(1) CONSTRAINT BOOK_LEND_BOOK_RETURN_YN_CK CHECK(BOOK_RETURN_YN IN ('Y','N'))
);
INSERT INTO LIBRARY VALUES('A-111', '어린왕자', '문예출판사', '2025-01-01');
INSERT INTO BOOK_LEND VALUES(100, 'A-111','2020-10-17','2020-10-20','Y');

SELECT * FROM LIBRARY;
SELECT * FROM BOOK_LEND;